### ISSUE TITLE
[tweets-analysis] [FIX] Script doesn't work with Pandas >= 1.0

### ISSUE THREAD

**Issue by luigigubello** [luigigubello/My-Twitter-World#2]
`tweets_analysis.py` doesn't work with Pandas >= 1.0. 

**Error:**
```
  File "tweets_analysis.py", line 120, in extract_datetime_feature
    df['weekday'] = df['tweet_time'].dt.dweekday_name.astype('category')  # Extract weekday (i.e. Monday, Friday)
AttributeError: 'DatetimeProperties' object has no attribute 'dweekday_name'
```

**How to fix:**
Going to [line 120](https://github.com/luigigubello/My-Twitter-World/blob/9df8b077f5d45f97abab03807f01a73cd6bf5d63/tweets-analysis/tweets_analysis.py#L120) and change `weekday_name` into `day_name()`.

I hope to fix it soon.
